name: Nova
version: ${project.version}
authors: [ "StudioCode", "ByteZ1337", "flimosch" ]
main: xyz.xenondevs.nova.Nova
api-version: 1.17
softdepend:
  - WorldGuard
  - GriefPrevention
  - GriefDefender
  - Vault
  - ItemsAdder