name: New Item Request
description: Suggest an idea for a new item.
title: "[Request - Item]"
labels: new item
body:
  - type: input
    attributes:
      label: Potential name of the item
      description: What should this item be named?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the item
      description: Describe what the item is and what it should be able to do.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
