name: Build Artifacts

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          server-id: xenondevs
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Run BuildTools
        run: . .github/scripts/buildtools.sh

      - name: Build With Maven
        run: mvn -B clean test package deploy "-Ddir=artifacts/" --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./Nova/artifacts/*.jar

      - name: Attach Artifacts
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./Nova/artifacts/*.jar
